site_name: Ranvier
site_description: "Ranvier is a Node.js-based MUD codebase built for modularity, extensibility and getting up-and-running in the least amount of time possible."
copyright: Copyright &copy; 2017, Shawn Biddle
site_author: Shawn Biddle
docs_dir: docs
repo_url: https://github.com/shawncplus/ranviermud
theme: null
theme_dir: docs/_mkdocs/theme/ranvier
extra:
    logo: '_static/images/logo.png'
markdown_extensions:
    - def_list
    - codehilite
    - toc:
        permalink: true
        title: 'Contents'
    - pymdownx.tasklist:
        custom_checkbox: true
google_analytics: ["UA-28253658-1", "auto"]

pages:
- Overview: index.md
- Get Started: get_started.md
- Server Config: server_config.md
- Project Structure: structure.md
- Extending:
    - Bundles: 'extending/bundles.md'
    - Areas:
        - Creating an Area: 'extending/areas/index.md'
        - Items: 'extending/areas/items.md'
        - NPCs: 'extending/areas/npcs.md'
        - Rooms: 'extending/areas/rooms.md'
        - Quests: 'extending/areas/quests.md'
        - Scripting: 'extending/areas/scripting.md'
    - Behaviors: 'extending/behaviors.md'
    - Channels: 'extending/channels.md'
    - Classes: 'extending/classes.md'
    - Commands: 'extending/commands.md'
    - Effects: 'extending/effects.md'
    - Events: 'extending/events.md'
    - Helpfiles: 'extending/help.md'
    - Skills: 'extending/skills.md'
